name: Ombre
version: '1.0.0'
main: dev.twme.ombre.Ombre
api-version: '1.21'
authors: [ TWME-TW ]
description: 允許玩家通過互動式 GUI 建立彩色漸層方塊效果
website: https://github.com/TWME-TW/Ombre

commands:
  ombre:
    description: 打開漸層製作 GUI 或執行其他子指令
    usage: |-
      /ombre - 打開漸層製作 GUI
      /ombre library - 打開共享庫
      /ombre favorites - 打開我的最愛
      /ombre stats - 查看統計數據
      /ombre admin - 管理員指令
      /ombre reload - 重新載入配置
      /ombre help - 查看幫助
    aliases: [om]
    permission: ombre.use
    permission-message: 你沒有權限使用此指令
  blockcolorsapp:
    description: 開啟 BlockColors.app 風格的顏色匹配 GUI
    usage: |-
      /blockcolorsapp - 開啟主介面
      /blockcolorsapp reload - 重新載入快取
      /blockcolorsapp cache - 查看快取狀態
      /blockcolorsapp clear-cache - 清除快取
    aliases: [bca]
    permission: ombre.blockcolorsapp.use
    permission-message: 你沒有權限使用此指令
  blockpalettes:
    description: 瀏覽 Block Palettes 社群調色板
    usage: |-
      /blockpalettes - 開啟主介面
      /blockpalettes favorites - 查看收藏
      /blockpalettes reload - 重新載入快取
      /blockpalettes cache - 查看快取狀態
      /blockpalettes terms - 查看條款資訊
      /blockpalettes help - 查看幫助
    aliases: [bp]
    permission: ombre.blockpalettes.use
    permission-message: 你沒有權限使用此指令

permissions:
  ombre.use:
    description: 基本使用權限（製作、儲存、收藏）
    default: true
  ombre.library:
    description: 瀏覽共享庫權限
    default: true
  ombre.publish:
    description: 發布配置到共享庫權限
    default: true
  ombre.admin:
    description: 管理員權限（刪除任意配置、重新載入）
    default: op
  ombre.blockcolorsapp.use:
    description: 使用 BlockColors.app 功能
    default: true
  ombre.blockcolorsapp.reload:
    description: 重新載入 BlockColors 快取
    default: op
  ombre.blockcolorsapp.admin:
    description: BlockColors 管理員權限
    default: op
  ombre.blockpalettes.use:
    description: 使用 Block Palettes 瀏覽功能
    default: true
  ombre.blockpalettes.reload:
    description: 重新載入 Block Palettes 設定
    default: op
  ombre.blockpalettes.terms.manage:
    description: 管理條款同意狀態
    default: op
