name: Ombre
version: '1.0.0'
main: dev.twme.ombre.Ombre
api-version: '1.21'
authors: [ TWME-TW ]
description: Allows players to create colored gradient block effects through an interactive GUI
website: https://github.com/TWME-TW/Ombre

commands:
  ombre:
    description: Open gradient creation GUI or execute other subcommands
    usage: |-
      /ombre - Open gradient creation GUI
      /ombre library - Open shared library
      /ombre favorites - Open favorites
      /ombre stats - View statistics
      /ombre admin - Admin commands
      /ombre reload - Reload configuration
      /ombre help - View help
    aliases: [om]
    permission: ombre.use
    permission-message: You don't have permission to use this command
  blockcolorsapp:
    description: Open BlockColors.app style color matching GUI
    usage: |-
      /blockcolorsapp - Open main interface
      /blockcolorsapp reload - Reload cache
      /blockcolorsapp cache - View cache status
      /blockcolorsapp clear-cache - Clear cache
    aliases: [bca]
    permission: ombre.blockcolorsapp.use
    permission-message: You don't have permission to use this command
  blockpalettes:
    description: Browse Block Palettes community palettes
    usage: |-
      /blockpalettes - Open main interface
      /blockpalettes favorites - View favorites
      /blockpalettes reload - Reload cache
      /blockpalettes cache - View cache status
      /blockpalettes terms - View terms information
      /blockpalettes help - View help
    aliases: [bp]
    permission: ombre.blockpalettes.use
    permission-message: You don't have permission to use this command

permissions:
  ombre.use:
    description: Basic usage permission (create, save, favorite)
    default: true
  ombre.library:
    description: Permission to browse shared library
    default: true
  ombre.publish:
    description: Permission to publish configurations to shared library
    default: true
  ombre.admin:
    description: Admin permission (delete any configuration, reload)
    default: op
  ombre.blockcolorsapp.use:
    description: Use BlockColors.app features
    default: true
  ombre.blockcolorsapp.reload:
    description: Reload BlockColors cache
    default: op
  ombre.blockcolorsapp.admin:
    description: BlockColors admin permission
    default: op
  ombre.blockpalettes.use:
    description: Use Block Palettes browsing features
    default: true
  ombre.blockpalettes.reload:
    description: Reload Block Palettes settings
    default: op
  ombre.blockpalettes.terms.manage:
    description: Manage terms agreement status
    default: op
